### ISSUE TITLE
Raw Data

### ISSUE THREAD

**Issue by BoazimMatrix** [aerorobotics/caltech-aerial-rgbt-dataset#2]
Hey,
Thank you for this great dataset.
I am trying to download some raw videos and I notice each video is a concat of 3 cameras.
So the left one is the RGB obviously, but what are the other two? Is the middle one the thermal camera or the right one?

Thank you

**Comment by AndersonRayner** [comment]
The left camera is RGB, the center is long-wave thermal (captured in 16-bit, converted to 8-bit for the video), and the right camera is mono-visible light which has a more sensitive sensor than the RGB camera.  For more details, you can check out our paper (https://arxiv.org/pdf/2403.08997), Section 3.1.
